server:
  port: 9999
spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:mysql://swagger.c3iqpeargbmp.ap-south-1.rds.amazonaws.com:3306/library
    username: admin
    password: mysqlswag
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true


